---
- hosts: test-server
  become: true
  tasks:
  - name: update apt
    command: apt update

  - name: install docker
    command: apt install -y docker.io

  - name: start docker service
    command: systemctl start docker

  - name: deploy insureme application
    command: docker run -itd -p 8083:8081 --name insure-me sunildh123/insureme:1.0
